# Generated by Django 4.2.3 on 2023-07-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('recipe', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
